name: 'MongoDB in GitHub Actions'
description: 'Start a MongoDB server (on default port 27017 or a custom port)'

branding:
  icon: 'database'
  color: 'green'

inputs:
  mongodb-version:
    description: 'MongoDB version to use (default "latest")'
    required: false
    default: 'latest'

  mongodb-replica-set:
    description: 'MongoDB replica set name (no replica set by default)'
    required: false
    default: ''

  mongodb-port:
    description: 'MongoDB port to use (default 27017)'
    required: false
    default: 27017

  mongodb-db:
    description: 'MongoDB db to create (default: none)'
    required: false
    default: ''

  mongodb-username:
    description: 'MongoDB root username (default: none)'
    required: false
    default: ''

  mongodb-password:
    description: 'MongoDB root password (default: none)'
    required: false
    default: ''

  mongodb-os:
    description: 'MongoDB runner os, if none it will read from runner.os (default: ubuntu-latest)'
    required: false
    default: ''
    options:
      - ubuntu-latest
      - ubuntu-22.04
      - ubuntu-20.04
      - macos
      - windows

runs:
  using: 'composite'
  steps:
    - name: Install MongoDB
      shell: bash
      run: |
        MONGODB_OS="${{ inputs.mongodb-os }}"
        if [ -z "$MONGODB_OS" ]; then
          if [[ "${{ runner.os }}" == Linux ]]; then
            # TODO: Parse version of Ubuntu?
            MONGODB_OS=ubuntu-22.04
          elif [[ "${{ runner.os }}" == Windows ]]; then
            MONGODB_OS=windows
          elif [[ "${{ runner.os }}" == macOS ]]; then
            MONGODB_OS=macos
          else
            "Unknown runner: \"${{ runner.os }}\""
          fi  
        fi
        ${GITHUB_ACTION_PATH}/start-mongodb.sh "${{ inputs.mongodb-version }}" \
        "${{ inputs.mongodb-replica-set }}" \
        "${{ inputs.mongodb-port }}" \
        "${{ inputs.mongodb-db }}" \
        "${{ inputs.mongodb-username }}" \
        "${{ inputs.mongodb-password }}" \
        "${MONGODB_OS}" \
        "${{ runner.temp }}"
