name: Start MongoDB Server

on: [push, pull_request]

jobs:
  mongodb-action:
    name: Start MongoDB Server v${{ matrix.mongodb-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.0.28', '4.2.25', '4.4.29', '5.0.26', '6.0.15', 'latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
